
  CREATE TABLE "TASY"."API_BLIP_PAS" 
   (	"NR_SEQ_SEGURADO" NUMBER NOT NULL ENABLE, 
	"NR_SEQ_NOTIFICACAO" NUMBER NOT NULL ENABLE, 
	"DS_MENSAGEM" LONG COLLATE "USING_NLS_COMP", 
	"CD_STATUS" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"DT_CRIACAO" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DT_VISUALIZACAO" DATE, 
	"DS_TITULO" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"CD_PERMISSAO" NUMBER DEFAULT 1 NOT NULL ENABLE
   ) 

